//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araclar()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int AracId { get; set; }
        public int MarkaNo { get; set; }
        public string Model { get; set; }
        public int ModelYili { get; set; }
        public int YakitTuruId { get; set; }
        public int SanzimanTuruId { get; set; }
        public decimal GunlukFiyat { get; set; }
        public bool KiradaMi { get; set; }
    
        public virtual Marka Marka { get; set; }
        public virtual SanzimanTuru SanzimanTuru { get; set; }
        public virtual YakitTuru YakitTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
